mod entities;
mod app_state;
mod routes;
mod repositories;
mod services;
mod dto;
mod errors;
mod openapi;

use app_state::AppState;
use axum::{
    routing::{get, post, put, delete},
    Router,
};
use std::env;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

use crate::openapi::ApiDoc;
use utoipa::OpenApi;
use tower_http::trace::TraceLayer;
use std::sync::Arc;
use axum::Json as AxumJson;
use axum::response::Html;


#[tokio::main]
async fn main() {
    tracing_subscriber::registry()
        .with(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "debug".into()),
        )
        .with(tracing_subscriber::fmt::layer())
        .init();

    dotenvy::dotenv().ok();

    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    let db = sea_orm::Database::connect(&database_url)
        .await
        .expect("Cannot connect to DB");

    let shared_state = Arc::new(AppState::new(db).expect("Invalid app state"));

    // Base API router (add routes)
    let api = Router::new()
        .route("/", get(routes::health::health_check))
        .route("/users", post(routes::users::create_user))
        .route("/users", get(routes::users::list_users))
        .route("/users/{id}", get(routes::users::get_user))
        .route("/users/{id}", put(routes::users::update_user))
        .route("/users/{id}", delete(routes::users::delete_user))
        // openapi json endpoint generated by utoipa
        .route("/api-doc/openapi.json", get(|| async { AxumJson(ApiDoc::openapi()) }))
        // serve a simple Swagger UI page that loads the above OpenAPI JSON
        .route("/swagger", get(|| async {
            Html(r#"
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Swagger UI</title>
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@4.18.2/swagger-ui.css" />
    <style>
    html, body { height: 100%; margin: 0; padding: 0; }
    #swagger-ui { height: 100vh; }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@4.18.2/swagger-ui-bundle.js"></script>
    <script>
    window.onload = () => {
        const ui = SwaggerUIBundle({
        url: "/api-doc/openapi.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
            SwaggerUIBundle.presets.apis,
            SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        });
        window.ui = ui;
    };
    </script>
</body>
</html>
            "#.to_string())
        }))
        .layer(TraceLayer::new_for_http())
        .with_state(shared_state);

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000")
        .await
        .unwrap();

    axum::serve(listener, api).await.unwrap();
}
