// src/openapi.rs
use utoipa::OpenApi;

// import handler functions (you already have these)
use crate::routes::users::{create_user, list_users, get_user, update_user, delete_user};
// ---- add these imports for the helper modules generated by #[utoipa::path]
use crate::routes::users::__path_create_user;
use crate::routes::users::__path_list_users;
use crate::routes::users::__path_get_user;
use crate::routes::users::__path_update_user;
use crate::routes::users::__path_delete_user;
// ---------------------------------------------------------------

use crate::dto::user_dto::{CreateUserRequest, UpdateUserRequest, UserResponse};

#[derive(OpenApi)]
#[openapi(
    paths(
        create_user,
        list_users,
        get_user,
        update_user,
        delete_user
    ),
    components(
        schemas(CreateUserRequest, UpdateUserRequest, UserResponse)
    ),
    tags(
        (name = "Users", description = "User management endpoints")
    )
)]
pub struct ApiDoc;
